return {
    "loggermanager",
	"status",
	"cfg.configmanager",
	"common.checkcmd",
	"common.msgmanager",
	"uimanager",
	"network",
	"login",
	"item.itemmanager",
	"common.timeutils",
	"character.settingmanager",
	"scenemanager",
	"ectype.ectypemanager",
	"character.pet.petmanager",
	"ui.rank.rankmanager",
	"character.fashionmanager",
    "character.characterinstpool",
	"character.skill.skillmanager",
	"character.skill.roleskill",
	"character.skill.traceweapon.flyingweaponmanager",
    "character.skill.traceweapon.bombmanager",
	"broadcastmanager",	
	
	--"ui.dlgmonster_hp",
	--"auth",
	"ui.chat.chatmanager",
	"character.charactermanager",
	"shopmanager",
	"ui.achievement.achievementmanager",-- 成就
	"ui.ride.ridemanager",
	"ui.mail.mailmanager",
	"ui.team.teammanager",
	"ui.updateattr.updateattrmanager",
	"ui.exchange.exchangemanager",
	"character.depotmanager",
	"ui.playerrole.playerrolemanager",
	"ui.activity.herochallenge.herochallengemanager",
	
	"ui.ectype.storyectype.storyectypemanager",
	"ui.ectype.multiectype.multiectypemanager",
	"ui.ectype.dailyectype.dailyectypemanager",
    "ui.ectype.guardtower.guardtowermanager",
	"ui.activity.worldboss.worldbossmanager",
	"ui.setting.graphicsettingmanager",
	"effect.camerashakemanager",
	"ui.operationactivity.operationactivitymanager",
	"effect.effectmanager",
	"audiomanager",
	"plot.plotmanager",
	"map.mapmanager",
	"prologue.prologuemanager",
	"cameramanager",
	"input.inputmanager",
	"character.dropmanager",
	"character.revivemanager",
	"assistant.errormanager",	
	"character.bagmanager",

	"character.curve.curvemodelmanager",
	"ui.modulelock.modulelockmanager",
	"assistant.infomanager",
	"limittimemanager",
	"ui.playerrole.equip.amuletmanager",
	"ui.cg.cgmanager",
	"character.ai.autoai",

	"ui.lottery.lotterymanager",-- 抽卡模块
	"ui.lottery.lotteryfragment.lotteryfragmentmanager",
	"ui.playerrole.storynote.storynotemanager",
	"taskmanager",
	"miningmanager",
	"ui.jade.jewelrybagmanager",
    "ui.citywar.citywarmanager",
	"ui.chat.jubaomanager",
    "ui.cornucopia.compressmanager",
	"family.familymanager",
	"item.bonusmanager",
	"ui.title.titlemanager",

	"noviceguide.noviceguidemanager",
	"ui.welfare.welfaremanager",
	"marriage.marriagemanager",
	"ui.maimai.maimaimanager",
    "guide.assistantmanager",
	"ui.activity.dlgactivitymanager",
	"ui.activity.activityexp.activityexpmanager",
	"ui.arena.modulearena",
	"ui.activity.tournament.tournamentmanager",
	"ui.activity.attackcity.attackcitymanager",
	"ui.activity.activitytipmanager",
	"ui.vipcharge.vipchargemanager",
	"ui.vipcharge.daychargemanager",
	"ui.shakemoney.moneytreemanager",
    "ui.activity.redpacket.redpacketmanager",
	"inited",--必须放在最后

}
