local Plot = require("plot.plot")

PlotCutscene = {
	PlayRate = 1,
	config = {
		isLooping = false,
		isSkippable = true,
		independentMusic = true,
		hideUI = true,
		hideCharacter = true,
		showBorder = true,
		showCurtain = true,
		fadeInOutTime = 0.7,
		mainCameraControl = true,
		previewMode = false,
	},
	StartTime = 0,
	Duration = 7,
	CurrentState = 5,
	AssetIndexList = {
		[1] = "MainCharacter",
	},
	Title = "xuzhang04",
	EndTime = 7,
	Type = "PlotDirector.PlotCutscene",
	ParentId = -1,
	PlotElements = {
		[1] = {
			ParameterCurveList = {
				[1] = {
					Name = "Time",
					KeyList = {
						[1] = UnityEngine.Keyframe(0,1,-0.6860206,-0.6860206),
						[2] = UnityEngine.Keyframe(3,0,-1.666481,-1.666481),
					},
				},
			},
			StartTime = 0,
			Duration = 3,
			CurrentState = 5,
			Title = "Blink Eye",
			EndTime = 3,
			Type = "PlotDirector.PlotEventCameraEffectBlinkEye",
			ParentId = 4,
		},
		[2] = {
			IndexName = "MainCharacter",
			Active = true,
			SetParent = false,
			ParentName = "",
			SetTrans = true,
			Position = Vector3(49.5,20.5,-2),
			Rotation = Vector3(-60,180,0),
			LocalScale = Vector3(1,1,1),
			ObjectName = "ZJ",
			StartTime = 0,
			Duration = 0.18,
			CurrentState = 5,
			Title = "Object Create",
			EndTime = 0.18,
			Type = "PlotDirector.PlotEventObjectCreate",
			ParentId = 3,
		},
		[3] = {
			ProfessionDeviation = false,
			PositionVary = true,
			RotationVary = true,
			ScaleVary = true,
			Position = Vector3(49.5,21.5,-1000),
			Rotation = Vector3(0,0,0),
			LocalScale = Vector3(1,1,1),
			StartTime = 0,
			Duration = 1,
			CurrentState = 5,
			Title = "Transform",
			EndTime = 1,
			Type = "PlotDirector.PlotEventCameraTransform",
			ParentId = 1,
		},
		[4] = {
			ObjectName = "ZJ",
			IsLoop = false,
			StateName = "dead",
			Layer = -1,
			NormalizedTime = 0,
			IsCrossFade = false,
			TransitionDuration = 0,
			StartTime = 0.18,
			Duration = 1,
			CurrentState = 5,
			Title = "Animator Play",
			EndTime = 1.18,
			Type = "PlotDirector.PlotEventAnimatorPlay",
			ParentId = 3,
		},
		[5] = {
			ObjectName = "ZJ",
			OnGround = false,
			OffSetY = 0,
			PathMode = "Bessel",
			TangentMode = false,
			PositionVary = true,
			RotationVary = true,
			ScaleVary = true,
			ConstSpeed = false,
			Speed = 7,
			PathList = {
				[1] = {
					NodeTime = 0,
					Position = Vector3(49.5,20.5,-2),
					Rotation = Vector3(300,180,0),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(49.5,20.5,-2),
					OutTangent = Vector3(49.5,20.5,-2),
				},
				[2] = {
					NodeTime = 0.01,
					Position = Vector3(49.5,20.5,-2),
					Rotation = Vector3(300,180,180),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(49.5,20.5,-2),
					OutTangent = Vector3(49.5,20.5,-2),
				},
			},
			StartTime = 1.18,
			Duration = 0.2,
			CurrentState = 5,
			Title = "Object Path",
			EndTime = 1.38,
			Type = "PlotDirector.PlotEventObjectPath",
			ParentId = 7,
		},
		[6] = {
			ObjectName = "ZJ",
			IsLoop = false,
			StateName = "standup",
			Layer = -1,
			NormalizedTime = 0,
			IsCrossFade = false,
			TransitionDuration = 0,
			StartTime = 1.18,
			Duration = 2.7,
			CurrentState = 5,
			Title = "Animator Play",
			EndTime = 3.88,
			Type = "PlotDirector.PlotEventAnimatorPlay",
			ParentId = 3,
		},
		[7] = {
			DialogMode = "DialogBox",
			DialogSystem = false,
			TalkId = 1,
			PersonPicture = "",
			TalkPerson = "",
			TalkContent = "主角：怎么又是这个梦，唔，这是在哪，算了，先到处看看吧。",
			UseSound = false,
			SoundPath = "",
			Position = Vector2(0,0),
			FontSize = -1,
			StartTime = 2.82,
			Duration = 4.18,
			CurrentState = 5,
			Title = "Talk",
			EndTime = 7,
			Type = "PlotDirector.PlotEventTalk",
			ParentId = 6,
		},
		[8] = {
			ObjectName = "ZJ",
			IsLoop = false,
			StateName = "idle",
			Layer = -1,
			NormalizedTime = 0,
			IsCrossFade = false,
			TransitionDuration = 0,
			StartTime = 3.88,
			Duration = 3.12,
			CurrentState = 5,
			Title = "Animator Play",
			EndTime = 7,
			Type = "PlotDirector.PlotEventAnimatorPlay",
			ParentId = 3,
		},
	},
}
setmetatable(PlotCutscene, {__index = Plot.PlotCutscene})
return PlotCutscene