local Plot = require("plot.plot")

PlotCutscene = {
	PlayRate = 1,
	config = {
		isLooping = false,
		isSkippable = false,
		independentMusic = false,
		hideUI = false,
		hideCharacter = false,
		showBorder = true,
		showCurtain = false,
		fadeInOutTime = 0.7,
		mainCameraControl = true,
		previewMode = false,
	},
	StartTime = 0,
	Duration = 1,
	CurrentState = 5,
	AssetIndexList = {
		[1] = "MainCharacter",
	},
	Title = "maincity_03_09",
	EndTime = 1,
	Type = "PlotDirector.PlotCutscene",
	ParentId = -1,
	PlotElements = {
		[1] = {
			ObjectName = "Role",
			OnGround = false,
			OffSetY = 0,
			PathMode = "Bessel",
			TangentMode = false,
			PositionVary = true,
			RotationVary = true,
			ScaleVary = true,
			ConstSpeed = false,
			Speed = 7,
			PathList = {
				[1] = {
					NodeTime = 0,
					Position = Vector3(7.666,35.828,-100),
					Rotation = Vector3(300,180,29.17),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(7.666,35.828,-100),
					OutTangent = Vector3(7.666,35.828,-100),
				},
				[2] = {
					NodeTime = 1,
					Position = Vector3(13.32,41.06,-100),
					Rotation = Vector3(300,180,20.76),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(13.32,41.06,-100),
					OutTangent = Vector3(13.32,41.06,-100),
				},
			},
			StartTime = 0,
			Duration = 1,
			CurrentState = 5,
			Title = "Object Path",
			EndTime = 1,
			Type = "PlotDirector.PlotEventObjectPath",
			ParentId = 2,
		},
		[2] = {
			IndexName = "MainCharacter",
			Active = true,
			SetParent = false,
			ParentName = "",
			SetTrans = true,
			Position = Vector3(7.92,34.96,-100),
			Rotation = Vector3(-60,180,0),
			LocalScale = Vector3(1,1,1),
			ObjectName = "Role",
			StartTime = 0,
			Duration = 1,
			CurrentState = 5,
			Title = "Object Special",
			EndTime = 1,
			Type = "PlotDirector.PlotEventObjectSpecialCreate",
			ParentId = 1,
		},
	},
}
setmetatable(PlotCutscene, {__index = Plot.PlotCutscene})
return PlotCutscene